### ISSUE TITLE
Specify strong with class or id

### ISSUE THREAD

**Issue by sangjunp4rk** [skyryoichi/Dasomoto#4]
Next time, make sure to specify your strong. For example, do `<strong class = “prices” >`. This makes your code more flexible as it grows in the future and you have to use span elsewhere. This way you can use it elsewhere if you just specify another class.

https://github.com/skyryoichi/Dasomoto/blob/master/Dasmoto/index.html#L22

**Comment by skyryoichi** [comment]
I have added class "prices" at strong code.
